# Functions generated by Clang.jl
include("./C/libhsl_ma77.jl")

function ma77_default_control(control) where T
  (T == Float32) && ma77_default_control_s(control)
  (T == Float64) && ma77_default_control_d(control)
end

function ma77_open_nelt(n, fname1, fname2, fname3, fname4, keep, control, info, nelt) where T
  (T == Float32) && ma77_open_nelt_s(n, fname1, fname2, fname3, fname4, keep, control, info, nelt)
  (T == Float64) && ma77_open_nelt_d(n, fname1, fname2, fname3, fname4, keep, control, info, nelt)
end

function ma77_open(n, fname1, fname2, fname3, fname4, keep, control, info) where T
  (T == Float32) && ma77_open_s(n, fname1, fname2, fname3, fname4, keep, control, info)
  (T == Float64) && ma77_open_d(n, fname1, fname2, fname3, fname4, keep, control, info)
end

function ma77_input_vars(idx, nvar, list, keep, control, info) where T
  (T == Float32) && ma77_input_vars_s(idx, nvar, list, keep, control, info)
  (T == Float64) && ma77_input_vars_d(idx, nvar, list, keep, control, info)
end

function ma77_input_reals(idx, length, reals, keep, control, info) where T
  (T == Float32) && ma77_input_reals_s(idx, length, reals, keep, control, info)
  (T == Float64) && ma77_input_reals_d(idx, length, reals, keep, control, info)
end

function ma77_analyse(order, keep, control, info) where T
  (T == Float32) && ma77_analyse_s(order, keep, control, info)
  (T == Float64) && ma77_analyse_d(order, keep, control, info)
end

function ma77_factor(posdef, keep, control, info, scale, nrhs, lx, rhs) where T
  (T == Float32) && ma77_factor_s(posdef, keep, control, info, scale, nrhs, lx, rhs)
  (T == Float64) && ma77_factor_d(posdef, keep, control, info, scale, nrhs, lx, rhs)
end

function ma77_factor_solve(posdef, keep, control, info, scale, nrhs, lx, rhs) where T
  (T == Float32) && ma77_factor_solve_s(posdef, keep, control, info, scale, nrhs, lx, rhs)
  (T == Float64) && ma77_factor_solve_d(posdef, keep, control, info, scale, nrhs, lx, rhs)
end

function ma77_solve(nrhs, flag_out, lx, x, keep, control, info, scale) where T
  (T == Float32) && ma77_solve_s(nrhs, flag_out, lx, x, keep, control, info, scale)
  (T == Float64) && ma77_solve_d(nrhs, flag_out, lx, x, keep, control, info, scale)
end

function ma77_resid(nrhs, lx, x, lresid, resid, keep, control, info, anorm_bnd) where T
  (T == Float32) && ma77_resid_s(nrhs, lx, x, lresid, resid, keep, control, info, anorm_bnd)
  (T == Float64) && ma77_resid_d(nrhs, lx, x, lresid, resid, keep, control, info, anorm_bnd)
end

function ma77_scale(scale, keep, control, info, anorm) where T
  (T == Float32) && ma77_scale_s(scale, keep, control, info, anorm)
  (T == Float64) && ma77_scale_d(scale, keep, control, info, anorm)
end

function ma77_enquire_posdef(d, keep, control, info) where T
  (T == Float32) && ma77_enquire_posdef_s(d, keep, control, info)
  (T == Float64) && ma77_enquire_posdef_d(d, keep, control, info)
end

function ma77_enquire_indef(piv_order, d, keep, control, info) where T
  (T == Float32) && ma77_enquire_indef_s(piv_order, d, keep, control, info)
  (T == Float64) && ma77_enquire_indef_d(piv_order, d, keep, control, info)
end

function ma77_alter(d, keep, control, info) where T
  (T == Float32) && ma77_alter_s(d, keep, control, info)
  (T == Float64) && ma77_alter_d(d, keep, control, info)
end

function ma77_restart(restart_file, fname1, fname2, fname3, fname4, keep, control, info) where T
  (T == Float32) && ma77_restart_s(restart_file, fname1, fname2, fname3, fname4, keep, control, info)
  (T == Float64) && ma77_restart_d(restart_file, fname1, fname2, fname3, fname4, keep, control, info)
end

function ma77_finalise(keep, control, info) where T
  (T == Float32) && ma77_finalise_s(keep, control, info)
  (T == Float64) && ma77_finalise_d(keep, control, info)
end

function ma77_solve_fredholm(nrhs, flag_out, lx, x, keep, control, info, scale) where T
  (T == Float32) && ma77_solve_fredholm_s(nrhs, flag_out, lx, x, keep, control, info, scale)
  (T == Float64) && ma77_solve_fredholm_d(nrhs, flag_out, lx, x, keep, control, info, scale)
end

function ma77_lmultiply(trans, k, lx, x, ly, y, keep, control, info, scale) where T
  (T == Float32) && ma77_lmultiply_s(trans, k, lx, x, ly, y, keep, control, info, scale)
  (T == Float64) && ma77_lmultiply_d(trans, k, lx, x, ly, y, keep, control, info, scale)
end

function ma77_finalize(keep, control, info) where T
  (T == Float32) && ma77_finalise(keep, control, info)
  (T == Float64) && ma77_finalise(keep, control, info)
end
