export JULIAHSL_isfunctional

# Wrappers generated by Clang.jl from C headers of HSL packages
include("C/juliahsl.jl")
include("C/hsl_ma48.jl")
include("C/hsl_ma57.jl")
include("C/hsl_ma77.jl")
include("C/hsl_ma86.jl")
include("C/hsl_ma87.jl")
include("C/hsl_ma97.jl")
include("C/hsl_mc64.jl")
include("C/hsl_mc68.jl")
include("C/hsl_mc69.jl")
include("C/hsl_mc78.jl")
include("C/hsl_mc79.jl")
include("C/hsl_mi20.jl")
include("C/hsl_mi28.jl")

# Wrappers for HSL packages written in Fortran 77
include("Fortran/kb07.jl")
include("Fortran/mc21.jl")
include("Fortran/mc77.jl")
