export JULIAHSL_isfunctional

# Wrappers generated by Clang.jl from C headers of HSL packages
include("C/juliahsl.jl")

# Wrappers for HSL packages written in Fortran 77
include("Fortran/kb07.jl")
include("Fortran/mc21.jl")
include("Fortran/mc77.jl")
