name: CI

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test-moonshot:
    env:
      CUDA_VISIBLE_DEVICES: 1
      JULIA_DEPOT_PATH: /scratch/github-actions/julia_depot_hsl
    runs-on: self-hosted
    strategy:
      matrix:
        os: [ubuntu-24.04]
        julia-version: ['1.10', '1.11']
        julia-arch: [x64]

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2
        with:
          file: lcov.info
