name: CI

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test-moonshot:
    env:
      CUDA_VISIBLE_DEVICES: 1
      JULIA_DEPOT_PATH: /scratch/github-actions/julia_depot_alexis
    runs-on: self-hosted
    strategy:
      matrix:
        os: [ubuntu-24.04]
        julia-version: ['1.10', '1.11']
        julia-arch: [x64]
        hsl-version: ['2024.11.28', '2025.7.21']

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/julia-buildpkg@latest
      - name: Set HSL_VERSION as environment variable
        run: echo "HSL_VERSION=${{ matrix.hsl-version }}" >> $GITHUB_ENV
      - name: Install HSL_jll.jl
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.activate("/scratch/github-actions/actions_runner_hsl/_work/HSL.jl/HSL.jl")
          path_HSL_jll = "/scratch/github-actions/actions_runner_hsl/HSL_jll.jl.v" * ENV["HSL_VERSION"]
          Pkg.develop(path=path_HSL_jll)
      - name: Test HSL.jl
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.develop(path=".")
          Pkg.test("HSL")
