name: CI_M1
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Julia ${{ matrix.version }} - macOS - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: [self-hosted, macOS]
    strategy:
      fail-fast: false
      matrix:
        version:
          # - '1.6'
          - '1'
          # - 'nightly'
        arch:
          - x64
          - aarch64
        # exclude:
        #   - version: '1.6'
        #     arch: aarch64
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Version Info
        shell: julia --color=yes {0}
        run: |
          using InteractiveUtils
          versioninfo()
      - uses: julia-actions/julia-buildpkg@v1
      - name: Install HSL_jll.jl
        shell: julia --color=yes {0}
        run: |
          using Pkg
          if VERSION ≥ v"1.9"
            Pkg.develop(path=ENV["HSL_JLL_LBT_PATH"])
          else
            Pkg.develop(path=ENV["HSL_JLL_OPENBLAS_PATH"])
          end
      - name: Test HSL.jl
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.test("HSL")
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info
